#!/bin/bash

# do publish

# find emacs executable file.
kernel=`uname -s`
emacs="emacs"
if [ $kernel"X" = "DarwinX" ]
then
    emacs="/Applications/Emacs.app/Contents/MacOS/Emacs"
fi

$emacs --batch --script publish.el
if [ $? != 0 ]
then
    echo "publish failed"
    exit 1
fi

# add some custom code.
./addcode

# rsync images and css files.
rsync -avrz images/ ../../dirtysalt.github.io/images/
rsync -avrz css/ ../../dirtysalt.github.io/css/
