* movie
#+TITLE: 电影
** memo
-----
【职场人士必看的十部经典电影】1《当幸福来敲门》；2《肖申克的救赎》；3《跳出我天地》；4《阿甘正传》；5《美丽心灵》；6《穿普拉达的女王》；7《面对巨人》；8《放牛班的春天》；9《天使艾米丽》；10《白色巨塔》。

-----
【经典“温暖人心”剧情片】《入殓师》《大鱼》《阳光小美女》《放牛班的春天》《天使爱美丽》《菊次郎的夏天》《天堂电影院》《蝴蝶》《蓝色大门》《曾经》《诺丁山》《真爱至上》《幸福终点站》《西雅图夜未眠》《当幸福来敲门》。

-----
【世上最美的10部电影】1.《公民凯恩》、 2.《猎人之夜》、 3.《游戏规则》、 4.《日出》、 5.《亚特兰大号》、 6.《M就是凶手》、 7.《雨中曲》、 8.《迷魂记》、 9.《天堂的孩子》、 10.《搜索者》，收藏好一部部看完！

-----
【唯美爱情电影推荐，你看过几部？】《假如爱有天意》《夏天协奏曲》《雏菊》《恋空》《海角七号》《情书》《触不到的恋人》《四月物语》《我脑海中的橡皮擦》《天使之恋》《比悲伤更悲伤的故事》《听说》《云中漫步》《七音符》《八月照相馆》《现在只想爱你》《恋爱小说》《向左爱向右爱》

** 当幸福来敲门(The Pursuit of Happiness)
** 肖申克的救赎(The Shawshank Redemption)
** 阿甘正传(Forrest Gump)
** 美丽心灵(A Beautiful Mind)
** 穿普拉达的女王(The Devil Wears Prada)
** 放牛班的春天(The Chorus)
** 天堂电影院(Nuovo cinema Paradiso)
** V字仇杀队(V for Vendetta)
** 赛德克巴莱(Seediq Bale)
-----

花冈一郎：“头目，被日本人统治不好吗？我们现在文明地生活，有学校，有邮局，不必再像从前一样依靠野蛮的猎杀而生存……被日本人统治难道不好吗？”

莫那·鲁道：“被日本人统治难道好吗！男人被迫弯下腰来搬运木头，女人被迫跪下膝来帮佣陪酒，该领的钱全进了日本警察的口袋……我这个当头目的除了每天喝醉了假装看不见听不见，还能怎么样！邮局、商店、学校，什么时候让族人的生活变得更好过？反倒让他们感觉到自己有多贫穷了！”

花冈一郎：“头目，我们就再忍二十年好吗……”

莫那·鲁道：“再过二十年就不会再有赛德克人，不会再有猎场，孩子就全都变成日本人了！！”

莫那·鲁道：“达奇斯（花冈一郎），喝酒吧！回去以后喝他个大醉吧！……喝吧！我们酿的酒可以让人无拘无束，让人手舞足蹈、哭笑随性，大醉一场之后你就会懂了！回去吧！”

-----

花冈一郎：“您又不是不知道日本有多少军队……这么做只不过是白白牺牲而已！您上次不是还说日本人比森林里的……”

莫那·鲁道：“日本人比森林里的树叶还要繁密，比浊水溪里的石头还要多，但是我反抗的决心比奇莱山还要坚定！如果你所谓的文明是让我们卑躬屈膝，那我就让你们看一看野蛮的骄傲！……达奇斯，你这个从来不想了解自己民族的子孙给我听好，‘赛德克·巴莱’可以输掉身体，但是一定要赢得灵魂！！”

-----

塔道·诺干：“你明明知道这一战一定会败，为什么还要去打！”

莫那·鲁道：“为了就要被遗忘的图腾！你看这些年轻人白白净净的脸，没有赛德克人应有的纹面图腾，你忍心看他们死后的灵魂被祖灵遗弃？还是你觉得他们不够资格成为一个双手染血的‘赛德克·巴莱’？”

塔道·诺干：“……图腾？”

莫那·鲁道：“图腾！”

塔道·诺干：“用生命去换取图腾，那用什么来换回这些年轻的生命！！”

莫那·鲁道：“骄傲！！”

-----

莫那·鲁道：“十五岁那年，我第一次出草，我也紧张胆怯、手脚发抖，但是我的眼神如箭！挥下敌人首级的瞬间，我忘记了什么叫做害怕，因为我知道我将作为勇士回到部落参加欢庆的酒宴，因为我知道从今以后部落里的男女老少都将尊敬我的勇猛！可是这次不一样！今天我们虽然成功血祭祖灵，取得了走过彩虹桥的资格，但是我门接下来要面对的不是酒宴的欢庆，而是选择死亡的方式！早在起事之前你们就知道这种结果了，不是吗！孩子们，别急着害怕！你们今天表现得很勇猛，祖灵们一定都看到了。但接下来要面对的才是真正的战斗，是要让异族人吓破肝胆的战斗！森林的祖灵鸟正驱赶着吃腐肉的乌鸦，水汽后的阳光只会让彩虹更加艳丽。孩子们啊，不要害怕，祖灵会肯定我们是守护猎场的好战士，你们手上的血痕就是印记，你们已经是赛德克巴莱了！！记住，一定要保持骄傲！我们要一起通过彩虹桥！”

-----

莫纳·鲁道：“如果所谓的文明就是让我们卑躬屈膝，那么就让你看看野蛮的骄傲！”

** 闻香识女人(Scent of a Woman)
Frank: I’ll show you out of order. You don’t know what out of order is, Mr. Trask, I’d show you, but I’m too old, I’m too tired, I’m too ****in’ blind, if I were the man I was five years ago, I’d take a flame thrower to this place! Out of order? Who the hell do you think you’re talkin’ to? I’ve been around, you know? There was a time I could see, and I have seen, boys like these, younger than these, their arms torn out, their legs ripped off, but there is nothin’ like the sight of an amputated spirit. There is no prosthetic for that, you think you’re merely sendin’ this splendid foot solider back home to Oregen with his tail between his legs, but I say you’re executin’ his soul! And why? Because he is not a Baird man. Baird men, you hurt this boy, you’re gonna be Baird bums, the lot of you. And Harry, Jimmy, and Trent, wherever you are out there, **** you too!

斯莱德中校：让你见识见识什么是破坏规矩，你不知道什么叫破坏规矩，垂斯克先生，真该让你见识，可我太老了，太累了，我他妈的还是个瞎子。要是五年前，我会拿火焰喷射剂把这给烧了！破坏规矩？你以为在跟谁说话？我可是久经沙场，那时候我还能看得见，我看见的是象他们这么大，甚至还要小孩子们胳膊被炸断了，腿被截肢了，可但那些都不及丑陋的灵魂可怕，因为灵魂没有义肢。你以为你只是把这个好青年像落水狗一样的送回俄勒冈的老家？？你们泯灭的是他的灵魂！！为什么？！就因为他不够做一个拜尔德人？拜尔德人，你们若是伤害了这个孩子，你们就是拜尔德的混蛋，你们全是。哈瑞、吉米、特伦特，不管你们坐在哪，见你们的鬼！

Frank: I’m not finished. As I came in here, I heard those words: cradle of leadership. Well, when the bough breaks, the cradle will fall, and it has fallen here, it has fallen. Makers of men, creators of leaders, be careful what kind of leaders you’re producin’ here. I don’t know if Charlie’s silence here today is right or wrong, I’m not a judge or jury, but I can tell you this: he won’t sell anybody out to buy his future! And that my friends is called integrity, that’s called courage. Now, that’s the stuff leaders should be made of. Now I have come to crossroads in my life, I always knew what the right path was. Without exception, I knew, but I never took it, you know why, it was too damn hard. Now here’s Charlie, he’s come to the crossroads, he has chosen a path. It’s the right path, it’s a path made of principle that leads to character. Let him continue on his journey. You hold this boy’s future in your hands, committee, it’s a valuable future, believe me. Don’t destroy it, protect it. Embrace it. It’s gonna make you proud one day, I promise you.

斯莱德中校：我还没说完呢，我刚一进到这里，就听到那些话：”未来领袖的摇篮”。如果架子断了，摇篮也就掉了，它已经随落了。造就青年、培养未来的领袖的人们，看吧！要小心了，你们在培养什么样的领袖，我不知道！今天查理保持沉默是对还是错，我虽然不是法官，但我可以告诉你，他不会为了自己的前途而出卖任何人。朋友们！这就是人们常说的正直，这就是勇气，这才是未来领袖所具有的品质。现在我到了一个人生的十字路口，我一向知道哪条路是正确的，毋庸置疑，我知道，可我从没走它，为什么？因为它太艰难了。轮到查理了，他也在一个人生的十字路口，他选择了一条路，一条有原则、成全他人格的路。让他沿着这条路继续前行吧，这孩子的前途掌握在你们的手里，委员们，他会前途无量的，相信我，别毁了他！保护他！支持他！我保证会有一天你们会为此而感到骄傲！我保证。

** 低俗小说(Pulp Fiction)
[Ezekiel 25:17. "The path of the righteous man is beset on all sides by the inequities of the selfish and the tyranny of evil men. Blessed is he who in the name of charity and good will, shepherds the weak through the valley of the darkness. For he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who attempt to poison and destroy my brothers. And you will know I am the Lord when I lay my vengeance upon you]

以西结书第25章第17节。“正义的人的道路给邪恶的人自私和暴行的不公平所包围。以慈悲和善意祝福他，他带领弱者走出黑暗的山谷，他是兄弟的守护者，以 及是迷途孩子的寻找人。而对于企图毒害和消灭我的兄弟的人，我会怀着巨大的愤怒和无比的仇恨去杀死他们。当我复仇的时候，他们将知道我的名字是耶和华。

** 勇敢的心(Brave Heart)
All right. Fight you may die, and run you will live at least for a while. And die in your beds many years from now, woule you be will to trade all those days from this day to that for a one chance, just one chance, to come back here, tell our enemies that they may take our lives, but they will never take our freedom

战斗可能会死去，逃跑还以苟活一阵子。日复一日，当你寿终正寝的时候，你是否愿意，用那些苟活的日子来交换一个机会，就今天这么一个机会，回到这里告诉我们的敌人，他们可能会夺取我们的生命，但是永远夺不走我们的自由。

** 拆弹部队(The Hurt Locker)
你喜欢玩所有的毛绒玩具,你喜欢妈妈,喜欢爸爸,喜欢你的小睡衣.你什么都喜欢.是不是?知道吗,等你长大了,曾经喜欢的东西也许会变得不再特别,就像这个玩偶盒,你会发现那只是一片铁皮加一个人偶.那些原本钟爱的东西会渐渐被你遗忘,到了我这个年纪,钟爱的东西也许只剩下一两件了,对我来说只剩一件了.

** 致命魔术(The Prestige)
Every great magic trick consists of three acts. The first act is called The Pledge: the magician shows you something ordinary, but of course, it probably isn't. The second act is called The Turn. The magician makes his ordinary something do something extraordinary. Now, if you're looking for the secret...you won't find it. That's why there's a third act, called The Prestige. This is the part with the twists and turns, where lives hang in the balance, and you see something shocking you've never seen before.

每一项伟大魔术的完成，都与三个过程密不可分：一为“验证”，魔术师展示了看似平常、实则已经动过手脚的表演道具；二为“转移”，魔术师手中看似普通的事物，瞬间变得与众不同，这个时候，如果你想找魔术背后的秘密……那几乎是不可能的，这也是为什么还会有第三步；三为“蒙蔽”，这也是魔术中最关键的环节，是魔术师利用技巧进行掩饰的过程，一旦达成某种平衡，就会产生那种前所未见、让你无比震惊的现象--也就是魔术。

** 林肯(Lincoln)
罗盘可以指明前进的方向，但它不会告诉你路上那里有高山、湖泊、沼泽，如果你一味前行，可能永远到不了目的地。

** 激战(Unbeatable)
原来，这个世界是不等人的。

我唯一做到的，都被我自己出卖了。

到了这个年纪，我们做一件事，还需要别人理解我们为什么去做吗？

** 纸牌屋(House of Cards)
** 绝命毒师(Breaking Bad)
** 华尔街(Wall Street)(1987)
** 拜金一族(Glengarry Glen Ross)(1992)
** 权利的游戏(Game of Thrones)
** 黑暗骑士崛起(The Dark Knight Rises)(2012)
** 黑暗骑士(The Dark Knight)(2008)
** 蝙蝠侠：侠影之谜(Batman Begins)(2005)
