* movie
#+TITLE: 电影
** Excerpt
-----
【职场人士必看的十部经典电影】1《当幸福来敲门》；2《肖申克的救赎》；3《跳出我天地》；4《阿甘正传》；5《美丽心灵》；6《穿普拉达的女王》；7《面对巨人》；8《放牛班的春天》；9《天使艾米丽》；10《白色巨塔》。

-----
【经典“温暖人心”剧情片】《入殓师》《大鱼》《阳光小美女》《放牛班的春天》《天使爱美丽》《菊次郎的夏天》《天堂电影院》《蝴蝶》《蓝色大门》《曾经》《诺丁山》《真爱至上》《幸福终点站》《西雅图夜未眠》《当幸福来敲门》。

-----
【世上最美的10部电影】1.《公民凯恩》、 2.《猎人之夜》、 3.《游戏规则》、 4.《日出》、 5.《亚特兰大号》、 6.《M就是凶手》、 7.《雨中曲》、 8.《迷魂记》、 9.《天堂的孩子》、 10.《搜索者》，收藏好一部部看完！

-----
【唯美爱情电影推荐，你看过几部？】《假如爱有天意》《夏天协奏曲》《雏菊》《恋空》《海角七号》《情书》《触不到的恋人》《四月物语》《我脑海中的橡皮擦》《天使之恋》《比悲伤更悲伤的故事》《听说》《云中漫步》《七音符》《八月照相馆》《现在只想爱你》《恋爱小说》《向左爱向右爱》

** 当幸福来敲门(The Pursuit of Happiness)
** 肖申克的救赎(The Shawshank Redemption)
** 阿甘正传(Forrest Gump)
** 美丽心灵(A Beautiful Mind)
** 穿普拉达的女王(The Devil Wears Prada)
** 放牛班的春天(The Chorus)
** 天堂电影院(Nuovo cinema Paradiso)
** V字仇杀队(V for Vendetta)
** 监守自盗(Inside Job)
美国大萧条之后从未出现过金融危机，并且金融业处于严格监管当中，同时大部分银行不允许使用储蓄存款用于投资交易。之后美国为了振兴经济，开始放宽了金融监管政策，比如银行允许使用储蓄存款进行风险投资，并且不希望对衍生的金融产品进行监管，而说服政府放宽政策的人就是华尔街投行。然后会发现，华尔街投行的高管逐渐进入政界学界，你发现美联储主席，财政部部长，哈佛大学经济学院院长，哈佛大学校长，哥伦毕业商学院院长等等，华尔街的意识形态也在逐渐渗透进入政界和学界。他们的利益基本上都是管理在一起的，可以称为华尔街的利益。然后就会发现，不管是什么政策和学术意见，都是代表着华尔街利益的。包括提高银行杠杆率，削减SEC的作用等等。

在原来，人们购房都是直接从房屋所有者或者是房产机构购买的。这些房屋所有者或者是房产结构，因为考虑到贷款时间的问题，所以都会仔细评估还款者的还款能力如何，并且要求付首付等等一系列措施。之后华尔街开始介入从房产机构中购买房本。因为房本是一种债务抵押关系，投行购买千万分这种债务抵押关系之后，打包成为CDO(Collateralized Debt Obligatiom,担保债务凭证)，然后将CDO作为让广大投资者购买。最终形成的产业链是这样的：购房者，房产机构，华尔街，投资者。华尔街的介入对于购房者没有什么影响，但是对于后三者非常有影响：
   - 房产机构因为自己资金有限，所以需要更多的资金来开发房子。
   - 华尔街虽然有一部分资金，但是它利用杠杆率(外部资产和自身资产比率)可以有更多的钱，这样可以赚更多的钱。
   - 投资者相对于购买国债和储蓄来比，回报率更高，因为房子都是在增值的(当时供小于求). 

但是能够有良好偿还能力的人还是相对少数，大部分人没有稳定的偿还能力。给这部分人的贷款，成为次贷。房产机构，华尔街，投资者三方面都想做大，但是有良好偿还能力的人有已经有房子了，所以他们开始拉入没有偿还能力的人，把次贷引入了。这里需要观察最重要的一点就是，房地产机构和华尔街都是拿到现钱的，最终次贷是被转嫁到投资者的。如果上游一旦开始不还钱的话，投资者拿到的只是一个个房产，而自己手上的钱全部没有了。并且因为房产到处都是，供大于求，造成房价跳水造成投资者的损失，而在这个过程中华尔街是最大的赢家。如果投资者知道是次贷的话，那么其实这些投资者是不会购买的，因为投资者也知道如果搞不好资金是回不来的。华尔街为了让投资者愿意购买，联合资产评价机构来对CDO进行评价。通过贿赂评价机构来对差的CDO高评，比如给AAA级别(和购买国债一样安全).本质上来说这相当于一种诈骗。

华尔街转手质量差的CDO一方面。因为它知道这个CDO很可能转手不了，那么就购买保险把。但是针对CDO这类投的保险比较特殊，称为CDS(Credit Default Swap,信用违约互换)。就好比B贷款给A,但是B害怕A某天还不了，所以向保险公司C投保CDS.这样如果A一旦还不了的话，那么由C来偿还B的损失，而B每年向C交纳一定的费用。但是问题是CDS允许贷款人之外也进行投保，这样一来保险公司每年收取的费用就更多了，但是风险就更大了。而当时监管不到位或者是没有规范，所以这样做就被允许了。片中举的例子，华尔街代表就是高盛，而保险公司就是AIG,高盛质量低劣的CDO向AIG进行投保，数量之大高盛自己都担心AIG偿还不起，所以自己还在其他保险公司投保了。

其实如果华尔街和保险公司，如果针对这种交易做风险管理的话，即使次贷真的来了也不会引起次贷危机，顶多投资者输钱但是华尔街和保险公司还是有充足的资金来确保经济的正常允许的。问题就在，华尔街和保险公司一旦将CDO和CDS转嫁出去之后，他们就立刻套现了也没有针对危机出现做什么预案，这就是为什么当时投行和保险公司红利是给足了。在泡沫没有爆破之前，每个人都很好。但是当泡沫出现之后，投资者发现CDO赚不到钱了，而银行和保险因为没有资金监管和风险预案，发现根本没有资金进行应付了(银行自己持有一些CDO导致资金缩水，而保险公司因为需要赔偿翻倍的CDS而缺少资金)。银行里面没有钱来贷款，而保险公司因为没有钱而不能够进行保险，导致整个经济停滞下来。其实反观最终的结果是什么，相当于投资人本应该用于生产的钱，一方面用于建设不必要的房产，另外一方面进入了少数利益集团的腰包了。

索罗斯一句比喻非常到位：市场天生就不稳定，至少存在不稳定的可能，就好比一个油轮非常庞大，我们必须将油舱分隔起来，这样可以防止油轮倾覆而导致大量原油泄漏。但是将油舱分隔开之后，就好比施加了很多金融监管政策，不利于资金的流动和刺激经济，这也就是为什么需要放宽它。放宽它有利于经济的振兴，但是潜在地我们需要承担更多的风险。也就像Rajan所说的，他们的做法是使用更大的风险获得更高的短期利润。但是问题是，更高的短期利润进入了少数利益集团的腰包，而更大的风险由中小投资者来承担了。

** 赛德克巴莱(Seediq Bale)
-----

花冈一郎：“头目，被日本人统治不好吗？我们现在文明地生活，有学校，有邮局，不必再像从前一样依靠野蛮的猎杀而生存……被日本人统治难道不好吗？”

莫那·鲁道：“被日本人统治难道好吗！男人被迫弯下腰来搬运木头，女人被迫跪下膝来帮佣陪酒，该领的钱全进了日本警察的口袋……我这个当头目的除了每天喝醉了假装看不见听不见，还能怎么样！邮局、商店、学校，什么时候让族人的生活变得更好过？反倒让他们感觉到自己有多贫穷了！”

花冈一郎：“头目，我们就再忍二十年好吗……”

莫那·鲁道：“再过二十年就不会再有赛德克人，不会再有猎场，孩子就全都变成日本人了！！”

莫那·鲁道：“达奇斯（花冈一郎），喝酒吧！回去以后喝他个大醉吧！……喝吧！我们酿的酒可以让人无拘无束，让人手舞足蹈、哭笑随性，大醉一场之后你就会懂了！回去吧！”

-----

花冈一郎：“您又不是不知道日本有多少军队……这么做只不过是白白牺牲而已！您上次不是还说日本人比森林里的……”

莫那·鲁道：“日本人比森林里的树叶还要繁密，比浊水溪里的石头还要多，但是我反抗的决心比奇莱山还要坚定！如果你所谓的文明是让我们卑躬屈膝，那我就让你们看一看野蛮的骄傲！……达奇斯，你这个从来不想了解自己民族的子孙给我听好，‘赛德克·巴莱’可以输掉身体，但是一定要赢得灵魂！！”

-----

塔道·诺干：“你明明知道这一战一定会败，为什么还要去打！”

莫那·鲁道：“为了就要被遗忘的图腾！你看这些年轻人白白净净的脸，没有赛德克人应有的纹面图腾，你忍心看他们死后的灵魂被祖灵遗弃？还是你觉得他们不够资格成为一个双手染血的‘赛德克·巴莱’？”

塔道·诺干：“……图腾？”

莫那·鲁道：“图腾！”

塔道·诺干：“用生命去换取图腾，那用什么来换回这些年轻的生命！！”

莫那·鲁道：“骄傲！！”

-----

莫那·鲁道：“十五岁那年，我第一次出草，我也紧张胆怯、手脚发抖，但是我的眼神如箭！挥下敌人首级的瞬间，我忘记了什么叫做害怕，因为我知道我将作为勇士回到部落参加欢庆的酒宴，因为我知道从今以后部落里的男女老少都将尊敬我的勇猛！可是这次不一样！今天我们虽然成功血祭祖灵，取得了走过彩虹桥的资格，但是我门接下来要面对的不是酒宴的欢庆，而是选择死亡的方式！早在起事之前你们就知道这种结果了，不是吗！孩子们，别急着害怕！你们今天表现得很勇猛，祖灵们一定都看到了。但接下来要面对的才是真正的战斗，是要让异族人吓破肝胆的战斗！森林的祖灵鸟正驱赶着吃腐肉的乌鸦，水汽后的阳光只会让彩虹更加艳丽。孩子们啊，不要害怕，祖灵会肯定我们是守护猎场的好战士，你们手上的血痕就是印记，你们已经是赛德克巴莱了！！记住，一定要保持骄傲！我们要一起通过彩虹桥！”

-----

莫纳·鲁道：“如果所谓的文明就是让我们卑躬屈膝，那么就让你看看野蛮的骄傲！”

** 教父(GodFather)
*** Excerpt
   - 这类事情每十年左右总要发生一次，这是恶感积累到一定程度的必然结果。如果咱们再小事情上让人家牵着鼻子走，他们就会得寸进尺，逼得咱们走投无路。
   - 一个人只有一个命运。
   - 我要同他讲道理。这是不流血又解决问题的最后机会。
   - 维托在年轻的时候就被认为是通情达理的人，他从来没有说过一句威胁的话，他始终使用的是不可抗拒的逻辑。他办事终归要根据的原则是：别人也得到了应得的一份利益，各方都不吃亏。他为达到这个目的，采用的是公开手法。他像许多天才商人一样懂得：自由竞争是浪费，垄断是有效的。因此他追求的目标就是要达到那种有效的垄断
   - 哪怕有些人眼瞎帮不了咱们的忙也要，我相信友谊，我也愿意首先表示我的友谊
   - 使用威胁乃是最愚蠢的自我暴露，事前不想想就大发脾气是最危险的任性表现。谁也没有听到过老头子脱口而出说过一句赤裸裸的威胁的话，
   - 谁也没有看到她发脾气的不能控制。就这样，他竭力把自己的戒律交给桑儿，他认为：人生除了有一个敌人过高估计你的缺点，就在没有更大的自然优势了。
   - 我为人一向谨慎小心。在生活中，我发现粗心大意最不和我的脾气。女人儿童粗心大意一下倒没有什么，男人以粗心大意就不得了。
   - 塔塔格里亚只不过是一个拉皮条，他根本不可能斗过桑蒂诺，这就是我为什么认为不必对事情进行调查了解的主要原因了。知道巴齐尼插手，这就足够了
   - 你对你所爱的人不能随便说‘不’字，也不能常常说，这就是诀窍。当你说‘不’字时，你得把‘不’字说得像‘是’字一样悦耳。另一个办法就是让他们说‘不’字。你得耐心，还得不怕麻烦。
   - 诀窍就是首先要发现哪个人不怕死，甚至找死。接着就是使你自己成为世界上他所希望的不要把他打死的唯一的人。他只有一个恐惧，不是怕死，而是怕你可能会成为打死他的人。做到这一部，那它就是你的贴心人了。
   - 一个男子汉在自己子女面前拿不出爸爸的气度出来，绝对不可能是真正的男子汉
   - 友谊就是一切，它比天赋更重要。朋友比政府更重要，朋友简直等于自家人。
   - 一个带着公事包的律师能够闭一百个带着枪的强盗榨取更多的财物
   - 千万别动肝火，千万不可作出威胁的样子，要和别人说理。说理的艺术就在于撇开一切侮辱，一切威胁。他打了你左脸，那么把右脸转过来让他再打。黑根曾经亲眼见过教父一连八个钟头稳坐在谈判桌旁，一再忍受侮辱，试图说服一个臭名昭著，狂妄自大，飞扬跋扈的狂人改过自新。八个钟头谈判无效，可里昂无可奈何的举起双手，对谈判桌旁其余人说：谁也无法和这号人说话。说完昂首阔步离开会议室。那个狂妄自大的人吓得脸色苍白，然后秘密请克利昂回到会议室。协议达成了，但是三个月后，那个狂人就在他常去的理发店被击毙。
   - 我希望你的事业能够继续兴旺发达，我们国家需要你从事的事业
   - 在克利昂一家的世界里，肉体美，女人的性魅力，在处理世俗事务的过程中一点分量也没有。男女之间的问题是无足轻重的私人小事，当然，除非涉及到婚姻和家庭荣辱。

*** 教父1(GodFather1)
人物：
   1. 维托柯里昂 纽约首领，教父
   2. 麦克柯里昂 三儿子，冷静能干，但是不愿意陷入家族事业
   3. 弗雷多柯里昂 二儿子，懦弱怕事
   4. 山提诺柯里昂 大儿子，冲动
   5. 康妮柯里昂 女儿
   6. 强尼方亭 教子
   7. 汤姆海根 教父的参谋私人律师
   8. 保利 教父的司机，属于克里门沙的手下
   9. 安索 面包师，是一个意大利人，来美国参战但是因为战争的结束可能会被遣返意大利，因为教父的原因能够留在美国:-)
   10. 克里门沙 教父手下
   11. 包纳萨拉 殡仪师，他的女儿被两个很有势力的人打得很重，但是自己没有办法对付那两个有势力的人，在教父的帮助下对付了两个有势力的人，后来帮助教父美容了一下满身疮痍的山提诺的尸体
   12. 巴西尼 黑帮家族
   13. 塔塔基利亚 黑帮家族
   14. 路卡布拉西 教父得力打手
   15. 华尔斯 好莱坞导演
   16. 布诺塔塔基利亚 塔塔基利亚家族人
   17. 麦克劳斯 纽约警局警长
   18. 路 索隆索的司机
   19. 卡洛 康妮的老公
   20. 汤马西诺 教父在西西里亚认识的人
   21. 艾波洛尼亚 麦克在西西里亚的妻子
   22. 法布里奇奥 麦克在西西里亚的保镖，但是被塔塔基利亚收买
   23. 卡罗 麦克在西西里亚的另一个保镖
   24. 卡麦克瑞安诺 布朗区首领
   25. 飞利浦塔塔基利亚 布鲁克林首领，塔塔基利亚家族首领
   26. 维多史特基 斯坦登岛首领
   27. 凯特 麦克的老婆
   28. 莫格林 拉斯维加斯赌场的经理，可以说是创建了拉斯维加斯赌城
   29. 沙尔泰西欧 教父手下 

故事实在是很难描述清楚，主线只有一条就是索隆索+塔塔基利亚+巴西尼家族和柯里昂家族的斗争，但是事情发展确实是很很曲折，这里面只是记录下一些重要的点，前几遍看的时候没有反应过来
   1. 和索隆索的谈判中，山提诺的一句话造成了教父的杀身之祸，因为索隆索知道教父没有心思介入毒品，但是他的儿子愿意，儿子继承父业就能够合作了
   2. 保利的叛变是在整个冬天都假装生病并且向索隆索报告了教父的出行习惯，在某个点才会出办公室并且回家，为索隆索的杀手汇报了情况。因为保利之前都是替教父开车的人
   3. 山提诺说漏嘴了教父就立刻派路卡布拉奇去杀掉索隆索，因为他知道事态的严重， 但是索隆索把路卡杀掉并且立刻封锁消息，直到后面通过西西里人的口信，就是路卡的防弹衣+一条死鱼告诉柯里昂家族，路卡和鱼长眠了。封锁消息然后让教父认为路卡成功打入塔塔基利亚内部，放松警惕，真是…
   4. 卡洛被巴奇尼收买并且殴打康妮，让山提诺冲动单独出行结果被塔塔基利亚家族干掉，这是因 为之前山提诺干掉了布诺塔塔基利亚，造成了事件的升级，因为之前只是索隆索和柯里昂家族的事情，现在到了塔塔基利亚和柯里昂家族之间的事情，这就是冲动的后果
   5. 沙尔泰西欧后来是不服麦克柯里昂的管理， 因为麦克柯里昂希望将自己的发展向内华达州前，而在此之前不希望泰西欧和克里门沙自立门户，而且承诺他们需要六个月才能够独立门户。泰西欧而认为这六个月如果不能够独立门户将会被巴西尼踩在头上，结果投靠了巴西尼家族:-(

*** 教父2(GodFather2)
人物：
   1. 保罗柯里昂 维托柯里昂的哥哥
   2. 西西欧 西西里亚的一个黑帮老大
   3. 安东尼柯里昂 维托柯里昂的儿子
   4. 玛莉柯里昂 维托柯里昂的女儿
   5. 法兰吉潘坦居利 以前属于克里门沙的手下,克里门沙死后归麦克管理
   6. 派特格瑞 内华达的一个参议院
   7. 威利奇奇 法兰吉潘坦居利的一个保镖
   8. 强尼欧拉 海门罗斯的一个助手
   9. 艾尔纳利 麦克柯里昂的一个保镖,这个人在第一部的时候最后面是去杀巴西尼的
   10. 罗萨罗 克里门沙打算死后把布朗区的三个地区给他处理,但是他算是海门罗斯的人
   11. 范伦奇 在维托柯里昂时代那个地区的黑手党的人
   12. 海门罗斯 维托柯里昂的一个合作伙伴,维托柯里昂尊敬他,但是从来不相信他:-)
   13. 汤马西诺 维托柯里昂在西西里的一个朋友 

-----
   1. 你的父亲尊重海门罗斯，但是他从来不相信海门罗斯
   2. 想想他们怎么想的，建立生意上面的话，没有什么事情是不可能发生的
   3. 历史的车轮告诉我们，没有人是干不掉的
   4. close to your firends,closer to your enemies

这集有很多人牵扯进来了，但是大部分都不是很重要，这里也只是写下一些要点的东西， 我比较喜欢第二部，因为第二部有着更多的利益冲突在里面而不仅仅是恐怖，而且如果需要恐怖的话，你可以站在mike的角度去找杀手的，你会觉得很恐怖。因为你不知道是法兰吉潘坦居利还是海门罗斯，两个人都是自己父亲的得力助手
   1. mike希望把在内华达和拉斯维加斯的赌场扩大到托比卡拉，在那边扩充赌场,但是那边没有营业执照，所以希望从派特格瑞这个内华达的参议员这里买到营业执照，但是派特格瑞将营业执照从2万提到25万，并且希望每个月能够收到4个赌场营业总额的5%，这是不能够接受的。 我猜应该是mike知道派特格瑞经常去妓院，所以故意弄出一件命案嫁祸给派特格瑞并且威胁他，这也是为什么之后派特格瑞被拉到柯里昂家族这边了，够手段:-)
   2. 我猜想第一次麦克柯里昂被刺杀的时候，怀疑的对象是法兰吉潘坦居利而不是海门罗斯。因为对于海门罗斯，麦克柯里昂一直没有采取什么行动，但是对于法兰吉，麦克柯里昂劝法兰吉去和罗萨罗讲和，并且告诉海门罗斯让罗萨罗杀掉法兰吉，但是法兰吉命大没有杀死，这也是之后法兰吉会去举报柯里昂是一个犯罪集团。虽然汤姆海根后来还和麦克柯里昂说”潘坦居利认为是你陷害他所以去揭发你”,但是麦克柯里昂之前的一句哈直接反映了这点”潘坦居利还活着??”，一个疑问句明显说明了麦克柯里昂第一次还是怀疑到了法兰吉的
   3. 麦克柯里昂最后确定是弗雷多窜通强尼欧拉和海门罗斯杀害他，是在哈瓦那的总统府看表演的时候，弗雷多说了一句”这个地方是强尼欧拉告诉我的”，而之前弗雷多和强尼欧拉见面的时候都假装不认识:-)
   4. 法兰吉潘坦居利最后自杀还是因为希望自己的家人能够保住性命:-)
   5. 汤马西诺在和维托柯里昂回西西里的时候，杀掉维托柯里昂的弑族仇人西西欧的时候，被一个强手打中了腿，这也是为什么第一部还有第三步，汤玛西诺先是一瘸一拐，后来是作在轮椅上的:-)

*** 教父3(GodFather3)
人物:
   1. 麦克柯里昂 第二代教父
   2. 玛莉柯里昂 麦克柯里昂女儿
   3. 安东尼柯里昂 麦克柯里昂儿子
   4. 乔扎萨 柯里昂在纽约生意的接管人
   5. 文森曼西尼 桑尼柯里昂的儿子
   6. 艾图贝洛 维多柯里昂的朋友
   7. 强尼方亭 维多柯里昂的教子
   8. 安东尼史基拉罗 乔扎萨的保镖
   9. 安德鲁海根 汤姆海根的儿子
   10. 特里莎海根 汤姆海根的妻子
   11. 安索 维多柯里昂帮助过的面包师
   12. 汤马西诺 维托柯里昂在西西里的朋友
   13. 鲁卡西 反对柯里昂掌管immobiliare的头头
   14. 龙巴度枢机主教 若望保禄一世
   15. 凯斯济 大主教的朋友[应该也掌握部分梵蒂冈银行的资金]
   
-----

   1. ”I protected all of you from all horror in the world.” “But you became my horror”
   2. Friendship and money, oil and water[朋友和金钱，像油和水一样].
   3. Never hate your enemies. It will affect your judgement.
   4. Never let anyone know what you are thinking
   5. Even the strongest man needs friends.
   6. But you know guns. Finance is a gun, politics is knowing when to put the trigger.
   7. you won’t be able to go back, you will be my being.[没有机会回头，步我的后尘]
   
-----

   1. 影片的开头叙述了上一部未完的事情就是弗雷多柯里昂的命运。麦克站在玻璃前面，接着湖上面一个枪声，接着麦克低下了头
   2. 麦克在授勋的时候看前妻Kate的眼神，真是感觉无限沧桑
   3. 文森曼西尼是桑尼柯里昂和外面女人胡搞生的，所以一直不被柯里昂家族所接受，也是文森曼西尼开始不认识玛利柯里昂的原因
   4. 注意麦克柯里昂所办的基金不是叫柯里昂基金，而是以父亲名字命名的维多柯良基金
   5. 教廷派大主教掌管梵蒂冈银行，同时梵蒂冈银行持有immobiliare的25%的股份。然后当时大主教损失了近8亿，然后这个时候麦克通过存入6亿美元来控制梵蒂冈银行以获得immobiliare的控制，但是最后梵蒂冈银行的决定还必须经由罗马教廷定夺，但是问题就是在这个时候罗马教皇[教宗保罗六世]一病不起，然后议程进入了僵局。
   6. 麦克之所以想进入immobiliare的原因是因为他想摆脱非法生意所以他也想解散赌场，但是出乎意料的是在那些看上去像是合法生意里面也充斥着非法的活动，充斥着卑劣的手段
   7. 麦克派出文森曼西尼探探艾图贝洛的关系如何…，从刺杀之后麦克就一直怀疑艾图贝洛，因为他知道乔扎萨的性格和实力不可能做出刺杀这种行动，而期间艾图贝洛又离席。但是他始终感觉艾图贝洛还是不够实力，所以派出曼西尼探艾图贝洛的关系网有多深….[而且他从汤马西诺口里也知道，艾图贝洛维护着西西里和美国友人的关系，所以关系网势必非常大]

   知道整个故事情节之后就知道第三部没有第一，二部好看。基本上里面的人物关系一开始就定下来了，没有任何转变的过程。相反觉得第二部非常好看，怀疑到了海门罗斯和法兰吉潘坦居利，通过两边有进行威慑最后发现是海门罗斯，但是同时法兰吉潘坦居利又变节指控麦克。最后追查海门罗斯在家族里面的内鬼居然是自己的弟弟。第一部也有这种查证过程，但是更加突出了恐怖的气氛。是不是黑帮电影内容都是这样:
   1. 涉及到了暗杀[1.杀害维多柯里昂和桑尼柯里昂 2.杀害麦克柯里昂 3.杀害麦克柯里昂]
   2. 找到凶手但是凶手都有后台[1.索隆索 2.凶手自杀了 3.乔扎萨]
   3. 找到后台[1.巴西尼和其他三大家族 2.海门罗斯 3.鲁卡西]
   
** 闻香识女人(Scent of a Woman)
Frank: I’ll show you out of order. You don’t know what out of order is, Mr. Trask, I’d show you, but I’m too old, I’m too tired, I’m too ****in’ blind, if I were the man I was five years ago, I’d take a flame thrower to this place! Out of order? Who the hell do you think you’re talkin’ to? I’ve been around, you know? There was a time I could see, and I have seen, boys like these, younger than these, their arms torn out, their legs ripped off, but there is nothin’ like the sight of an amputated spirit. There is no prosthetic for that, you think you’re merely sendin’ this splendid foot solider back home to Oregen with his tail between his legs, but I say you’re executin’ his soul! And why? Because he is not a Baird man. Baird men, you hurt this boy, you’re gonna be Baird bums, the lot of you. And Harry, Jimmy, and Trent, wherever you are out there, **** you too!

斯莱德中校：让你见识见识什么是破坏规矩，你不知道什么叫破坏规矩，垂斯克先生，真该让你见识，可我太老了，太累了，我他妈的还是个瞎子。要是五年前，我会拿火焰喷射剂把这给烧了！破坏规矩？你以为在跟谁说话？我可是久经沙场，那时候我还能看得见，我看见的是象他们这么大，甚至还要小孩子们胳膊被炸断了，腿被截肢了，可但那些都不及丑陋的灵魂可怕，因为灵魂没有义肢。你以为你只是把这个好青年像落水狗一样的送回俄勒冈的老家？？你们泯灭的是他的灵魂！！为什么？！就因为他不够做一个拜尔德人？拜尔德人，你们若是伤害了这个孩子，你们就是拜尔德的混蛋，你们全是。哈瑞、吉米、特伦特，不管你们坐在哪，见你们的鬼！

-----

Frank: I’m not finished. As I came in here, I heard those words: cradle of leadership. Well, when the bough breaks, the cradle will fall, and it has fallen here, it has fallen. Makers of men, creators of leaders, be careful what kind of leaders you’re producin’ here. I don’t know if Charlie’s silence here today is right or wrong, I’m not a judge or jury, but I can tell you this: he won’t sell anybody out to buy his future! And that my friends is called integrity, that’s called courage. Now, that’s the stuff leaders should be made of. Now I have come to crossroads in my life, I always knew what the right path was. Without exception, I knew, but I never took it, you know why, it was too damn hard. Now here’s Charlie, he’s come to the crossroads, he has chosen a path. It’s the right path, it’s a path made of principle that leads to character. Let him continue on his journey. You hold this boy’s future in your hands, committee, it’s a valuable future, believe me. Don’t destroy it, protect it. Embrace it. It’s gonna make you proud one day, I promise you.

斯莱德中校：我还没说完呢，我刚一进到这里，就听到那些话：”未来领袖的摇篮”。如果架子断了，摇篮也就掉了，它已经随落了。造就青年、培养未来的领袖的人们，看吧！要小心了，你们在培养什么样的领袖，我不知道！今天查理保持沉默是对还是错，我虽然不是法官，但我可以告诉你，他不会为了自己的前途而出卖任何人。朋友们！这就是人们常说的正直，这就是勇气，这才是未来领袖所具有的品质。现在我到了一个人生的十字路口，我一向知道哪条路是正确的，毋庸置疑，我知道，可我从没走它，为什么？因为它太艰难了。轮到查理了，他也在一个人生的十字路口，他选择了一条路，一条有原则、成全他人格的路。让他沿着这条路继续前行吧，这孩子的前途掌握在你们的手里，委员们，他会前途无量的，相信我，别毁了他！保护他！支持他！我保证会有一天你们会为此而感到骄傲！我保证。

** 低俗小说(Pulp Fiction)
[Ezekiel 25:17. "The path of the righteous man is beset on all sides by the inequities of the selfish and the tyranny of evil men. Blessed is he who in the name of charity and good will, shepherds the weak through the valley of the darkness. For he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who attempt to poison and destroy my brothers. And you will know I am the Lord when I lay my vengeance upon you]

以西结书第25章第17节。“正义的人的道路给邪恶的人自私和暴行的不公平所包围。以慈悲和善意祝福他，他带领弱者走出黑暗的山谷，他是兄弟的守护者，以 及是迷途孩子的寻找人。而对于企图毒害和消灭我的兄弟的人，我会怀着巨大的愤怒和无比的仇恨去杀死他们。当我复仇的时候，他们将知道我的名字是耶和华。

** 勇敢的心(Brave Heart)
All right. Fight you may die, and run you will live at least for a while. And die in your beds many years from now, woule you be will to trade all those days from this day to that for a one chance, just one chance, to come back here, tell our enemies that they may take our lives, but they will never take our freedom

战斗可能会死去，逃跑还以苟活一阵子。日复一日，当你寿终正寝的时候，你是否愿意，用那些苟活的日子来交换一个机会，就今天这么一个机会，回到这里告诉我们的敌人，他们可能会夺取我们的生命，但是永远夺不走我们的自由。

** 拆弹部队(The Hurt Locker)
   - 你喜欢玩所有的毛绒玩具,你喜欢妈妈,喜欢爸爸,喜欢你的小睡衣.你什么都喜欢.是不是?知道吗,等你长大了,曾经喜欢的东西也许会变得不再特别,就像这个玩偶盒,你会发现那只是一片铁皮加一个人偶.那些原本钟爱的东西会渐渐被你遗忘,到了我这个年纪,钟爱的东西也许只剩下一两件了,对我来说只剩一件了.

** 致命魔术(The Prestige)
Every great magic trick consists of three acts. The first act is called The Pledge: the magician shows you something ordinary, but of course, it probably isn't. The second act is called The Turn. The magician makes his ordinary something do something extraordinary. Now, if you're looking for the secret...you won't find it. That's why there's a third act, called The Prestige. This is the part with the twists and turns, where lives hang in the balance, and you see something shocking you've never seen before.

每一项伟大魔术的完成，都与三个过程密不可分：一为“验证”，魔术师展示了看似平常、实则已经动过手脚的表演道具；二为“转移”，魔术师手中看似普通的事物，瞬间变得与众不同，这个时候，如果你想找魔术背后的秘密……那几乎是不可能的，这也是为什么还会有第三步；三为“蒙蔽”，这也是魔术中最关键的环节，是魔术师利用技巧进行掩饰的过程，一旦达成某种平衡，就会产生那种前所未见、让你无比震惊的现象--也就是魔术。

** 林肯(Lincoln)
   - 罗盘可以指明前进的方向，但它不会告诉你路上那里有高山、湖泊、沼泽，如果你一味前行，可能永远到不了目的地。

** 激战
   - “原来，这个世界是不等人的。” 
   - “我唯一做到的，都被我自己出卖了。” 
   - “到了这个年纪，我们做一件事，还需要别人理解我们为什么去做吗？”

** 纸牌屋(House of Cards)
** 绝命毒师(Breaking Bad)
