* tj-car-checkout
#+TITLE: 天津验车

-----

2013 年天津市验车流程

如果你是新车买了两年后第一次验车的话,想好了你打算在哪个区验车,先去那个区的交警支队落户。其实落户挺简单的,只是把你行车证里的那个磁卡刷一下就可以了，而且是免费的(不像有的人忽悠你落户需要多少钱的)。但是前提是你要把需要的东西带齐了,所需要的东西是:
1. 身份证原件及复印件(一定不要过期了)
2. 行驶证的原件和复印件(正本和副本都要复印,副本就是后面那个写着你下次验车时间的那个卡片)。 原件复印是你车照片背面哦,不要你车照片的复印件。 *???*
3. 暂住证原件及复印件(如果你是外地人的话),也是里面的两张卡片全部复印, 当然暂住证一定是在有效期之内的, 不然也是没用的, 还需要你重新去你居住地派出所重新办理的。
4. 以上复印件需要清楚哦,不要有什么遮挡物,不然你还需要重新复印的。当你把以上东西交给办事民警后, 对方将磁卡信息读入系统后就完成落户了。
5. 交车船税,在支队时一定要把车船税交了。

验车:
1. 排队刷卡,在车务大厅排队,你把行驶证磁卡给办事人员后,复印件,如果没带复印间的话,他那可以复印,一元一份。
2. 车架号拓印:每种车型的车架号所在位置不同,有的在发动机舱内,有的在副驾驶座位下,有的在主驾驶座位下,如果你的车铺地胶了,那就忍痛吧,让他们把地胶割开。
3. 检测线验车:拓印完车架号后,就是开车进检测线了,你把车开到门口后,下车走人,到出口处等你的车,里面验车是由工作人员开车进行检测的。检测表上检测项挺多的。你的灭火器,警示架等什么的一定要带上,不然会有不合格项的。还有验车前尽量把车洗干净了,方便工作人员对你的爱车进行检测。不然怕有什么不合格项等着你滴。具体的检测项没有仔细的看,反正像尾气排放,大灯什么的都要检测。如果你的车大灯改过了, 那就改回来吧, 不然肯定过不去的。
4. 等你的车开出来后,工作人员下来后没说你的车有什么问题的话, 那恭喜你, 你的车检测过关了。到窗口把你的检测表给工作人员,他会给你黄绿标和一张副本的。
5. 如果你没有违章的话那就车务大厅里把检测表给工作人员,让他把资料并档,等他核实完后会给你行驶证副本和检验标志,行驶证副本是告诉你下次验车是什么时候。检验标志一定要即使张贴到你的前挡风玻璃上,不然让警察叔叔发现了,你的银子又该减少了。
6. 如果你有违章的,好像需要去支队把违章消除了,在那里会有工作人员在你交完罚款后,给你行驶证副本及检验标志。当你拿到这些后,表明你的车验完了。可以放心的上路了。



